name: Backend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci-cd.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci-cd.yml'

permissions:
  contents: read

jobs:
  lint_test:
    name: Lint & Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install Backend Dependencies
        run: npm ci --prefix backend

      - name: Lint Backend Code
        run: npm run lint --prefix backend

      - name: Run Backend Tests
        run: npm run test --prefix backend

  deploy_to_render:
    name: Deploy Backend to Render
    needs: lint_test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Trigger Render Deploy (Backend)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_BACKEND }}